### ISSUE TITLE
runing apis-main

### ISSUE THREAD

**Issue by subaruclover** [SonyCSL/apis-main#4]
I have several questions about running apis-main:

1.  With `bash start.sh`, connection refused, error message as follows:
(HARDWARE:LOCAL:ERROR:E001) Communication failed with Device Driver ; io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:4390 [jp.co.sony.csl.dcoes.apis.main.app.controller.DeviceControlling$Sender_.lambda$executeWithRetry_$1(DeviceControlling.java:511)]

The error message pops after `bash start2.sh`, `bash start3.sh`, `bash start4.sh`, communication connection among different apis-main could not be established.

2. What is the expected output with running apis-main alone? Is it Log files?

3. Is the dcdc exchange 1-to-1 or N-to-N? So far, I have observed 1-to-1, 1-to-2,  2-to-1 power exchange between different apis-mains. 
<img width="657" alt="dcdc" src="https://user-images.githubusercontent.com/22536753/127487481-dd5543ed-49f0-47fa-aba8-78a10982168c.png">

4. Is it possible to have dynamic changes in the `scenario.json` files for energy sharing?

**Comment by dai-kawamo** [comment]
Thank you for clone the software!

1. apis-main get the data from emulator in the default setting. If emulator is not running this error occurs.
2. apis-main cannot run alone and need to run emulator. Log file is in apis-main directory.
3. The exchange is 1-to-1 and individual exchange is done by deal. If one unit join two deals, it seems that 1-to-2 or 2-to-1 is occuring. Deal information is in the left side of apis-main_controller (localhost:4382)
